##== general
quitOnTopLevelReturn: true
##== gui
gui:
  nerdFontsVersion: "3"
  mouseEvents: false
  showRootItemInFileTree: false
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - blue
##== git
git:
  paging:
  colorArg: always
  pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="Dracula"
  log:
    showGraph: always
  diffRenderers:
    - colorArg: always
      command: delta --paging=never
##== keymap
keybinding:
  universal:
    quit: "q"
    nextTab: "]"
    prevTab: "["
  files:
    commitChanges: "c"
